name: macOS CI

on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Sketch dependencies (sketchtool install)
      - name: Install Sketch tool
        run: |
          set -xeu
          [[ -x sketchtool/bin/sketchtool ]] && exit 0
          curl -L -o sketch.zip https://download.sketch.com/sketch-100.3-180165.zip
          unzip -qo sketch.zip
          #cp -rp Sketch.app/Contents/Resources/sketchtool/bin/sketchtool ./sketchtool

      - name: Install libicns
        uses: ConorMacBride/install-package@v1
        with:
          brew: libicns

      # Export and Import Images using the sketchtool export
      - name: Export Images from Sketch
        run: |
          #!/bin/bash
          dest_dir="out/png"
          sketchtool=Sketch.app/Contents/Resources/sketchtool/bin/sketchtool

          # Export Jianfengzhi.sketch
          mkdir -p "$dest_dir/Jianfengzhi"
          ${sketchtool} export slices "Jianfengzhi.sketch" --output="$dest_dir/Jianfengzhi"

          # Export Pure.sketch
          mkdir -p "$dest_dir/Pure"
          ${sketchtool} export slices "Pure.sketch" --output="$dest_dir/Pure"

      - name: Convert png to icns
        run: |
          #!/bin/bash
          src_dir="out/png"
          dest_dir="out/icns"
          
          # Convert PNG files to ICNS (Jianfengzhi)
          mkdir -p "$dest_dir/Jianfengzhi"
          png2icns "$dest_dir/Jianfengzhi/*.icns" "$src_dir/Jianfengzhi/*.png"

          # Convert PNG files to ICNS (Pure)
          mkdir -p "$dest_dir/Pure"
          png2icns "$dest_dir/Pure/*.icns" "$src_dir/Pure/*.png"

      # Upload the output images as an artifact
      - name: Upload Exported Images
        uses: actions/upload-artifact@v3
        with:
          name: exported-images
          path: out/images
          if-no-files-found: error  # Options: warn, error, ignore
          retention-days: 30        # Retain the artifact for 30 days
          include-hidden-files: false  # Do not include hidden files
