name: macOS CI

on:
  push:
  pull_request:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Sketch dependencies (sketchtool install)
      - name: Install Sketch tool
        run: |
          set -xeu
          [[ -x sketchtool/bin/sketchtool ]] && exit 0
          curl -L -o sketch.zip https://download.sketch.com/sketch-100.3-180165.zip
          unzip -qo sketch.zip
          #cp -rp Sketch.app/Contents/Resources/sketchtool/bin/sketchtool ./sketchtool

      # Export and Import Images using the sketchtool export
      - name: Export Images from Sketch
        run: |
          #!/bin/bash
          dest_dir="out/images"
          sketchtool=Sketch.app/Contents/Resources/sketchtool/bin/sketchtool

          # Export Jianfengzhi.sketch
          mkdir -p "$dest_dir/Jianfengzhi"
          ${sketchtool} export slices "Jianfengzhi.sketch" --output="$dest_dir/Jianfengzhi"

          # Export Pure.sketch
          mkdir -p "$dest_dir/Pure"
          ${sketchtool} export slices "Pure.sketch" --output="$dest_dir/Pure"

      - name: ImageMagick action
        uses: jruipinto/ImageMagick-action@v1
        with:
          # ImageMagick command to be executed
          command: magick mogrify -format icns *.png

      # Upload the output images as an artifact
      - name: Upload Exported Images
        uses: actions/upload-artifact@v3
        with:
          name: exported-images
          path: out/images
          if-no-files-found: error  # Options: warn, error, ignore
          retention-days: 30        # Retain the artifact for 30 days
          include-hidden-files: false  # Do not include hidden files
